export const ArrForRender = [
  {
    key: 0,
    tittle: "Guilt",
    author: "Nero",
    album: "Welcome Reality",
    trackTime: "4:44",
  },
  {
    key: 1,
    tittle: "Elektro",
    author: "Dynoro, Outwork, Mr. Gee",
    album: "Elektro",
    trackTime: "2:22",
  },
  {
    key: 2,
    tittle: "I’m Fire",
    author: "Ali Bakgor",
    album: "I’m Fire",
    trackTime: "2:22",
  },

  {
    key: 3,
    tittle: "Non Stop",
    comment: "(Remix)",
    author: "Стоункат, Psychopath",
    album: "Non Stop",
    trackTime: "4:12",
  },

  {
    key: 4,
    tittle: "Run Run",
    comment: "(feat. AR/CO)",
    author: "Jaded, Will Clarke, AR/CO ",
    album: " Run Run",
    trackTime: "2:54",
  },
  {
    key: 5,
    tittle: "Eyes on Fire",
    comment: "(Zeds Dead Remix)",

    author: "Blue Foundation, Zeds Dead",
    album: "Eyes on Fire",
    trackTime: "5:20",
  },
  {
    key: 6,
    tittle: "Mucho Bien",
    comment: "(Hi Profile Remix)",
    author: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
    album: "Mucho Bien",
    trackTime: "3:41",
  },
  {
    key: 7,
    tittle: "Knives n Cherries",
    author: "minthaze",
    album: "Captivating",
    trackTime: "1:48",
  },
  {
    key: 8,
    tittle: "Knives n Cherries",
    author: "minthaze",
    album: "Captivating",
    trackTime: "1:48",
  },
  {
    key: 9,
    tittle: "Knives n Cherries",
    author: "minthaze",
    album: "Captivating",
    trackTime: "1:48",
  },
  {
    key: 10,
    tittle: "Knives n Cherries",
    author: "minthaze",
    album: "Captivating",
    trackTime: "1:48",
  },
  {
    key: 11,
    tittle: "Knives n Cherries",
    author: "minthaze",
    album: "Captivating",
    trackTime: "1:48",
  },
  {
    key: 12,
    tittle: "Knives n Cherries",
    author: "minthaze",
    album: "Captivating",
    trackTime: "1:48",
  },
  {
    key: 13,
    tittle: "Knives n Cherries",
    author: "minthaze",
    album: "Captivating",
    trackTime: "1:48",
  },

  {
    key: 14,
    tittle: "How Deep Is Your Love",
    author: "Calvin Harris, Disciples",
    album: "How Deep Is Your Love",
    trackTime: "3:32",
  },
  {
    key: 15,
    tittle: "Morena",
    author: "Tom Boxer",
    album: "Soundz Made in Romania",
    trackTime: "3:36",
  },
];
