// Здесь будут константы для активного трека

export const START_TRACK = "START_TRACK"

export const PAUSE_TRACK = "PAUSE_TRACK"

export const UNPAUSE_TRACK = "UNPAUSE_TRACK"

export const CHANGE_PLAYLIST = "CHANGE_PLAYLIST"

export const UPDATE_HISTORY = "UPDATE_HISTORY"

export const REMOVE_HISTORY = "REMOVE_HISTORY"

export const READY = "READY"

export const ADD_LIKE_STARTED = "ADD_LIKE_STARTED"
export const ADD_LIKE_SUCCESS = "ADD_LIKE_SUCCESS"
export const ADD_LIKE_FAILURE = "ADD_LIKE_FAILURE"

export const DELETE_LIKE_STARTED = "DELETE_LIKE_STARTED"
export const DELETE_LIKE_SUCCESS = "DELETE_LIKE_SUCCESS"
export const DELETE_LIKE_FAILURE = "DELETE_LIKE_FAILURE"


