// Здесь будут константы для активного трека

export const START_TRACK = "START_TRACK"

export const PAUSE_TRACK = "PAUSE_TRACK"

export const UNPAUSE_TRACK = "UNPAUSE_TRACK"

export const CHANGE_PLAYLIST = "CHANGE_PLAYLIST"

export const UPDATE_HISTORY = "UPDATE_HISTORY"

export const REMOVE_HISTORY = "REMOVE_HISTORY"

export const READY = "READY"

export const ADD_LIKE_STARTED = "ADD_LIKE_STARTED"
export const ADD_LIKE_SUCCESS = "ADD_LIKE_SUCCESS"
export const ADD_LIKE_FAILURE = "ADD_LIKE_FAILURE"

export const REMOVE_LIKE_STARTED = "REMOVE_LIKE_STARTED"
export const REMOVE_LIKE_SUCCESS = "REMOVE_LIKE_SUCCESS"
export const REMOVE_LIKE_FAILURE = "REMOVE_LIKE_FAILURE"

